[tool.mypy]
files = "model"
show_error_codes = true
pretty = true
warn_unused_ignores = true
warn_redundant_casts = true
no_implicit_optional = true
check_untyped_defs = true
implicit_reexport = false


[[tool.mypy.overrides]]
module = [
    "torchvision.*",
    "mlflow.*",
    "torch.*",
    "ultralytics.*",
]
ignore_missing_imports = true

[tool.isort]
line_length = 120
profile = "black"
skip_glob = "**/__init__.py"


[tool.black]
line-length = 120
target-version = ['py38']

